version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        EnableExecuteCommand: true
        LoadBalancerInfo:
          ContainerName: "otel1"
          ContainerPort: 9876
