version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "IMAGE_ADDRESS"
        LoadBalancerInfo:
          ContainerName: "otel1"
          ContainerPort: 9876
