version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p6d6n2q4
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t otel1:latest .
      - docker tag otel1:latest public.ecr.aws/p6d6n2q4/otel1:latest
      - docker tag otel1:latest public.ecr.aws/p6d6n2q4/otel1:v$CODEBUILD_BUILD_NUMBER      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to public repo
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p6d6n2q4
      - docker push public.ecr.aws/p6d6n2q4/otel1:latest
      - docker push public.ecr.aws/p6d6n2q4/otel1:v$CODEBUILD_BUILD_NUMBER
      - echo pushing to private repo
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 525158249545.dkr.ecr.us-west-2.amazonaws.com
      - docker tag otel1:latest 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1-private:latest
      - docker tag otel1:latest 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1-private:v$CODEBUILD_BUILD_NUMBER
      - docker push 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1-private:latest
      - docker push 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1-private:v$CODEBUILD_BUILD_NUMBER
      - echo Writing image definitions file for codepipeline https://docs.aws.amazon.com/codepipeline/latest/userguide/file-reference.html...
      - printf '[{"name":"otel1-private","imageUri":"%s"}]' 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1-private:v$CODEBUILD_BUILD_NUMBER > imageDetail.json
artifacts:
    files: 
    - imagedefinitions.json
    - taskdef.json
    - appsec.yaml

