# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: otel1
  labels:
    name: otel1
---

apiVersion: v1
kind: Service
metadata:
  name: cp
  namespace: otel1
spec:
  clusterIP: None
  selector:
    app: otel1
  ports:
  - name: http
    port: 4080
    targetPort: 4080

---

# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel1
  namespace: otel1
  labels:
    name: aws-otel-eks-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel1
      app: otel1
  template:
    metadata:
      labels:
        name: otel1
        app: otel1
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 0
      containers:
        - name: otel1
          image: 525158249545.dkr.ecr.us-west-2.amazonaws.com/otel1:v10
          env:
            - name: OTEL_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: FIRST_ADMIN_USER
              value: admin
            - name: FIRST_ADMIN_PASSWORD
              value: Simplepass#123
            - name: DATA_PATH
              value: /go/bin/data
          # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1024m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 4080
              name: http
          volumeMounts:
          - name: data
            mountPath: /go/bin/data
        - name: aws-otel-collector
          image: public.ecr.aws/aws-observability/aws-otel-collector:latest
          env:
            - name: AWS_REGION
              value: us-west-2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 24Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: default
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 10Gi


