# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: otel1
  labels:
    name: otel1
---

apiVersion: v1
kind: Service
metadata:
  name: otel1
  namespace: otel1
spec:
  type: ClusterIP
  selector:
    app: otel1
  ports:
  - name: http
    port: 9876
    targetPort: 9876

---

# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel1
  namespace: otel1
  labels:
    name: aws-otel-eks-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel1
      app: otel1
  template:
    metadata:
      labels:
        name: otel1
        app: otel1
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 0
      containers:
        - name: otel1
          image: public.ecr.aws/p6d6n2q4/otel1:v9
          env:
            - name: OTEL_OTLP_GRPC_ENDPOINT
              value: "0.0.0.0:4317"
            - name: OTEL_OTLP_HTTP_ENDPOINT
              value: "localhost:55681"
            - name: PORT
              value: "9876"
          # command: ["/bin/bash", "-c", "while true; do sleep 1; done"] # for debugging
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 64m
              memory: 100Mi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 9876
              name: http
        - name: aws-otel-collector
          image: public.ecr.aws/aws-observability/aws-otel-collector:latest
          env:
            - name: AWS_REGION
              value: us-west-2
          # command:
          #   - /awscollector
            # - --set=service.telemetry.logs.level=debug
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 24Mi


